server:
  port: 8081 #服务端口

spring:
  application:
    name: microservice-iv #指定服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: QOGIR

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000 #设置hystrix的超时开启保护时间 ms
